---
title: "ExtraOvuleNumber_2025"
output: html_document
date: "2025-09-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
remove(list = ls())
```


Load Packages
```{r, warning=FALSE, message=FALSE}
library(MASS)
library(tidyverse)
library(lme4)
library(lmerTest)
library(car)
library(emmeans)
library(ggpubr)

```


Load data
```{r}
data <- read.csv("Raw Data/Data/Ovule_Count_2025.csv", header = TRUE)
meta <- read.csv("Raw Data/Data/Ovule_Count_2025_meta.csv", header = TRUE)

```


### Format ovule data
```{r}

data_all <- merge(meta, data, by = c("Plant_ID", "Sex"))

# Drop observations with stigmas that have a length affected by herbivory and create a variable based on if there is female function or not
data_all2 <- data_all %>% 
  filter(Stigma_Herbivory != 1) %>% 
  mutate(female_func = if_else(Ovule_Count == 0, 0, 1))

```



### Separate binomial and number
```{r}
# Female function
# Ovule production binary
ovule_binom.m <- glmer(female_func ~ Sex * Stigma_Length + Plot + (1|Plant_ID), data = data_all2, family = "binomial")

summary(ovule_binom.m)
Anova(ovule_binom.m)

RE_ovule_binom.m <- glm(female_func ~ Sex * Stigma_Length + Plot, data = data_all2, family = "binomial")
anova(ovule_binom.m, RE_ovule_binom.m)


emmeans(ovule_binom.m, specs = pairwise ~ Sex, type = "response")

stigma_all$ovule_binom_predict <- predictInterval(ovule_binom.m, 
                                                  stigma_all,
                                                  which = "full",
                                                  level = 0.95,
                                                  n.sims = 1000,
                                                  stat = "mean",
                                                  type = "probability",
                                                  include.resid.var = TRUE,
                                                  returnSims = FALSE,
                                                  seed = 2,
                                                  .parallel = FALSE,
                                                  .paropts = NULL,
                                                  fix.intercept.variance = FALSE,
                                                  ignore.fixed.terms = NULL)


(ov_plot1 <- ggplot(data_all2, aes(x = Stigma_Length, y = female_func)) +  
  geom_jitter(height = 0.15, color = "black") +
  geom_smooth(method = "glm", se = T, 
        method.args = list(family = "binomial"), 
        color = "black") +
  theme_classic()+  
  ylab("Mean Female Function \n(Likelihood of Ovule Production)") +
  xlab("Stigma Length (mm)")+
  theme(legend.position = "none"))



# Are there functional males?
(ov_plot2 <- data_all2 %>% 
  dplyr::select(Sex, Plant_ID, female_func) %>% 
  mutate(Sex = if_else(Sex == "F", "Female", "Hermaphrodite")) %>% 
  na.omit(female_func) %>% 
    group_by(Sex, Plant_ID) %>%  
  mutate(mean_female_func = mean(female_func, na.rm = TRUE),
         Number = n()) %>%
  ungroup() %>%
  mutate(Plant_ID = factor(Plant_ID, levels = 
                             unique(Plant_ID[order(mean_female_func)]))) %>%
  ggerrorplot(x="Plant_ID", y="female_func",
              color="Sex", palette=c("#7A378B", "#66CD00"),
              desc_stat = "mean_se",
              position = position_dodge(0.3),
              size = 0.05,
              xlab="Individual Plants", 
              ylab="Mean Female Function \n(Likelihood of Ovule Production)",
              facet.by = "Sex") +
  geom_point(aes(x=Plant_ID, y=mean_female_func, 
                 size = Number, color = Sex), alpha = 0.1) +
  labs(size = "Sample Size") +
  theme(axis.text.x = element_blank(), 
        axis.ticks.x = element_blank(),
        legend.position = "right"))


stigma_all %>% 
  drop_na(female_func) %>% 
  group_by(Sex, Population, Plant_ID) %>% 
  mutate(mean_female_func = mean(female_func, na.rm = TRUE)) %>% 
  filter(mean_female_func == 0) %>% 
  summarise(n = n())

```

### Ovule Number
```{r}
# Ovule Number
ovule1 <- stigma_all %>% filter(female_func == 1)

q1_ovule_num.m <- glmer.nb(Ovule_Number_1 ~ Sex * Stigma_Length + Population + (1|Plant_ID), data = ovule1, verbose = TRUE)

summary(q1_ovule_num.m)
Anova(q1_ovule_num.m)

check_overdispersion(q1_ovule_num.m)


RE_ovule_num.m <- MASS::glm.nb(Ovule_Number_1 ~ Sex * Population* Stigma_Length, 
                         data = ovule1, trace = TRUE)
anova(q1_ovule_num.m, RE_ovule_num.m)


ggplot(ovule1, aes(x = Sex, y = Ovule_Number_1, fill = Sex)) +
  geom_violin(alpha = 0.25) +
  geom_boxplot(width = 0.15) +
  theme_classic()+  
  ylab("Ovule Number") +
  scale_fill_manual(values = c("#7A378B", "#66CD00"))+
  facet_wrap(vars(Population)) +
  theme(legend.position = "none")


```

Floral Trait multipanel figure
```{r}
FloralTrait_Panel <- ggarrange(ggarrange(stig_plot, ov_plot1, ncol = 2, nrow = 1, labels = c("A", "B")), ov_plot2, nrow = 2, labels = c("", "C"), heights = c(1, 1.5))

ggsave("Figures/FloralTrait_Panel.png", width = 8, height = 6, units = "in")
```

